FROM debian:12-slim

# INIT: docker build -t ebpf-compiler .
# BUILD BINARY:
#   docker run --rm -v "$(pwd)":/app ebpf-compiler clang -O2 -target bpf -c /app/ja4t_kern.c -o /app/ja4t_kern.o

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    clang \
    llvm \
    libelf-dev \
    zlib1g-dev \
    libbpf-dev \
    bpftool \
    linux-headers-generic && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

