FROM golang:1.24-bookworm AS builder

RUN apt-get update && apt-get install -y \
    clang \
    llvm \
    bpftool \
    libelf-dev \
    libbpf-dev \
    build-essential \
    git \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /repo
